# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API version 2
Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12"
  config.ssh.username = "vagrant"

  config.vm.provider "vmware_desktop" do |vmware|
    vmware.vmx["memsize"] = "1024"
    vmware.vmx["numvcpus"] = "2"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "2"
  end

  config.vm.define "JinamS" do |server|
    server.vm.hostname = "JinamS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "k3s-master.sh"
  end
  config.vm.define "JinamSW" do |worker|
    worker.vm.hostname = "JinamSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", path: "k3s-worker.sh", args:["192.168.56.110"]
  end
end
