apiVersion: v1
kind: ConfigMap
metadata: 
  name: app1-html
data:
  index.html: |
    <!doctype html>
    <html>
      <body>
        <h1>APP 1</h1>
        <p> Routed by app1.com </p>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment #Deployment, Service, Ingress ConfigMap, Secret
metadata:
  name: app1
spec: # deployment 에게 할일 알려주기 
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template: # pod 의 설계도 
    metadata:
      labels:
        app: app1
    spec:
      containers: # pod 안에서 실행할 컨테이너 목록 
        - name: app1
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: html
          configMap:
            name: app1-html
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
