Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.define "JinamS" do |server|
    server.vm.hostname = "JinamS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "vmware_desktop" do |vmware|
      vmware.vmx["memsize"] = "1024"
      vmware.vmd["numvcpus"] = "1"
    end
    server.vm.provision "shell", path: "scripts/install-k3s.sh"
  end
end

  

